### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by toussetz** [diskria-minecraft/atd#5]
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-08-25 19:58:30
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_161.method_686()" because "this.advancement" is null
	at com.diskree.achievetodo.advancements.UnblockActionToast.method_1986(UnblockActionToast.java:34)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)
	at net.minecraft.class_757.method_3192(class_757.java:972)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.diskree.achievetodo.advancements.UnblockActionToast.method_1986(UnblockActionToast.java:34)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)

-- Affected level --
Details:
	All players: 1 total; [class_746['Toussetz'/244, l='ClientLevel', x=34.66, y=59.00, z=21.54]]
	Chunk stats: 1024, 442
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,0), Section: (at 0,8,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4122 game time, 4122 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by diskria** [comment]
thanks, I'll fix it in the next update, server support is something new for me and it takes time to bring it to stable

**Comment by toussetz** [comment]
I managed to fix it, my mistake was that I moved the already existing world to the folder with the server, it was right for the server to create the world itself
But there was another error, achievements refuse to count

**Comment by diskria** [comment]
Are you using the latest version of the mod?  Please download the latest if you are not sure.
Also, you must have the blazeandcaves datapack in the datapacks folder of the world and specify `file/bacap.zip`(required file name) in `enabled-packs` in `server.properties`

**Comment by toussetz** [comment]
yes i am using the latest version
and the datapack is installed https://prnt.sc/AJCq_8aGdokp

**Comment by diskree** [comment]
type `/datapacks list` plz

**Comment by diskria** [comment]
I just now noticed that you are using a vanilla server.  You should to install the achievetodo mod on the server side bcz the mod is mixed

**Comment by toussetz** [comment]
i use this core https://quiltmc.org/en/install/server/ and mod is in mods folder
I assume that I somehow install the datapack incorrectly, because when I drag an already created world into the server folder, it crashes, but the achievements are counted
but when i create a world on the server nothing works
Can you please describe how you install the datapack on the server?

**Comment by diskria** [comment]
@toussetz you need to stop server, clear the save folder on the server, then create a `datapacks` folder in it and move `bacap.zip` into it, then specify it in `enabled-packs` in config and after that start the server. The world will be created correctly

**Comment by diskria** [comment]
did you get it to run?
