### ISSUE TITLE
I can't launch Minecraft.

### ISSUE THREAD

**Issue by Everty24** [diskria-minecraft/atd#6]
Picked up _JAVA_OPTIONS: -Xmx512M
[22:23:39] [INFO] [Quilt Loader/GameProvider]: Loading Minecraft 1.20.1 with Quilt Loader 0.19.5
[22:23:53] [ERROR] [Quilt Loader/]: Uncaught exception in thread "main"
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.iterator(ArrayList.java:947)
	at org.quiltmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:320)
	at org.quiltmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:247)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:380)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[22:23:39] [INFO] [Quilt Loader/Mappings]: Loading mappings: jar:file:/C:/Users/%d0%bf%d0%ba/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/quiltmc/hashed/1.20.1/hashed-1.20.1.jar!/mappings/mappings.tiny
[22:23:39] [INFO] [Quilt Loader/Mappings]: Skipping mappings: Missing namespace 'intermediary'
[22:23:39] [INFO] [Quilt Loader/Mappings]: Loading mappings: jar:file:/C:/Users/%d0%bf%d0%ba/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar!/mappings/mappings.tiny
[22:23:39] [WARN] [Quilt Loader/GameRemap]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Quilt know!
[22:23:39] [INFO] [Quilt Loader/GameRemap]: Preparing JARs on first launch, this may take a few seconds...
---- Crashed! ----
Date/Time: 2023/08/28 22:23:53.9666

-- Crash --

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.iterator(ArrayList.java:947)
	at org.quiltmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:320)
	at org.quiltmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:247)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:380)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

-- Mods --

| Index | Mod | ID | Version | Type | File Hash (SHA-1) | File(s) |
|------:|-----|----|---------|------|-------------------|---------|
|------:|-----|----|---------|------|-------------------|---------|
Mod Table Version: 2
Plugin Types: {}

---- end of report ----

**Comment by diskria** [comment]
you don't have enough RAM, allocate more
