### ISSUE TITLE
Is it possible to install this modpack on a remote server?

### ISSUE THREAD

**Issue by happykostas** [diskria-minecraft/atd#9]

**Comment by happykostas** [comment]
I tried to put modpack on the server, but when getting achievements the game with the client crashes, with the server everything is fine

**Comment by diskria** [comment]
incomplete error log. also, format this please in code block

**Comment by happykostas** [comment]
Yeah, sorry, I didn't realize it right away. It's supposed to be full logs now
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-09-09 17:13:54
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_161.method_686()" because "this.advancement" is null
	at com.diskree.achievetodo.advancements.UnblockActionToast.method_1986(UnblockActionToast.java:34)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)
	at net.minecraft.class_757.method_3192(class_757.java:972)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.diskree.achievetodo.advancements.UnblockActionToast.method_1986(UnblockActionToast.java:34)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)
Mixins in Stacktrace:
	net.minecraft.class_374:
		me.flashyreese.mods.sodiumextra.mixin.toasts.MixinToastManager (#sodium-extra:sodium-extra.mixins.json)
		dynamicfps.mixin.ToastManagerMixin (#dynamicfps:dynamicfps.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['LonelyPandaren'/529, l='ClientLevel', x=-61.25, y=53.32, z=15.04]]
	Chunk stats: 1024, 447
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,117,48), Section: (at 0,5,0 in -4,7,3; chunk contains blocks -64,-64,48 to -49,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 78263 game time, 102263 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_638:
		dev.lambdaurora.lambdynlights.mixin.ClientWorldMixin (#lambdynlights:lambdynlights.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.biome.ClientWorldMixin (#sodium:sodium.mixins.json)
		net.coderbot.iris.mixin.vertices.block_rendering.MixinClientLevel (#iris:mixins.iris.vertexformat.json)
		dev.tr7zw.entityculling.mixin.ClientWorldMixin (#entityculling:entityculling.mixins.json)
		xaero.map.mixin.MixinClientWorld (#xaeroworldmap:xaeroworldmap.mixins.json)
		org.quiltmc.qsl.lifecycle.mixin.client.ClientWorldMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		me.steinborn.krypton.mixin.client.fastchunkentityaccess.ClientWorldMixin (#krypton:krypton.mixins.json)
		dev.architectury.mixin.fabric.client.MixinClientLevel (#architectury:architectury.mixins.json)
		org.quiltmc.qsl.entity.event.mixin.client.ClientWorldMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.map.ClientWorldMixin (#sodium:sodium.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (#lithium:lithium.mixins.json)
	net.minecraft.class_310:
		jerozgen.languagereload.mixin.MinecraftClientAccessor (#languagereload:languagereload.mixins.json)
		org.quiltmc.qsl.registry.mixin.client.MinecraftClientMixin (#quilt_registry:quilt_registry.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (#yet_another_config_lib_v3:yacl.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (#tcdcommons:tcdcommons.client.mixin.events.json)
		xaero.map.mixin.MixinMinecraftClient (#xaeroworldmap:xaeroworldmap.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (#sodium:sodium.mixins.json)
		dynamicfps.mixin.MinecraftClientMixin (#dynamicfps:dynamicfps.mixins.json)
		com.minenash.customhud.mixin.MinecraftClientMixin (#custom_hud:customhud.mixins.json)
		dev.tr7zw.exordium.mixin.MinecraftMixin (#exordium:exordium.mixins.json)
		org.quiltmc.qsl.base.mixin.client.MinecraftClientMixin (#quilt_base:quilt_base.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (#spruceui:spruceui.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (#fallingleaves:fallingleaves.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (#languagereload:languagereload.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (#citresewn-defaults:citresewn-defaults.mixins.json)
		org.quiltmc.qsl.command.mixin.client.MinecraftClientMixin (#quilt_client_command:quilt_client_command.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.MinecraftClientMixin (#quilt_screen:quilt_screen.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (#blur:mixins.blur.json)
		io.socol.betterthirdperson.mixin.MinecraftClientMixin (#betterthirdperson:betterthirdperson.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (#iris:mixins.iris.json)
		org.quiltmc.qsl.networking.mixin.accessor.MinecraftClientAccessor (#quilt_networking:quilt_networking.mixins.json)
		ca.fxco.moreculling.mixin.MinecraftClient_managersMixin (#moreculling:moreculling.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (#kirin:kirin.mixin.json)
		de.siphalor.mousewheelie.client.mixin.MixinMinecraftClient (#mousewheelie:mousewheelie.mixins.json)
		ca.fxco.moreculling.mixin.blockstates.MinecraftClient_loadBlocksMixin (#moreculling:moreculling.mixins.json)
		org.quiltmc.qsl.lifecycle.mixin.client.MinecraftClientMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (#quilted_fabric_registry_sync_v0:quilted_fabric_registry_sync_v0.client.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (#sodium-extra:sodium-extra.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (#iris:mixins.iris.json)
		com.diskree.achievetodo.mixins.client.MinecraftClientMixin (#achievetodo:achievetodo.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (#ferritecore:ferritecore.fabric.mixin.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (#quilted_fabric_events_interaction_v0:quilted_fabric_events_interaction_v0.client.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.client.MinecraftClientMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (#quilted_fabric_data_generation_api_v1:quilted_fabric_data_generation_api_v1.client.mixins.json)
		de.siphalor.amecs.impl.mixin.MixinMinecraftClient (#amecsapi:amecsapi.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (#architectury:architectury.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (#satin:mixins.satin.client.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (#iris:mixins.iris.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (#lambdynlights:lambdynlights.mixins.json)
```

**Comment by happykostas** [comment]
I also want to note that I used datapacks when creating the world. The world itself I generated first on the local computer, and then transferred it to the server. Maybe that's important too

**Comment by diskria** [comment]
Ok, I'll try to fix this when I have time. Most likely this is a problem only for the server. Please make sure once again that the mod is installed on both the server and the client side

**Comment by happykostas** [comment]
I checked everything a few more times, all mods are installed on both the server and the client side.
Thanks, I hope you can solve this problem soon. And also thanks for the modpack, I played it in singleplayer, I really liked it.

**Comment by happykostas** [comment]
How is it going?

**Comment by diskria** [comment]
I'm currently working an update with Minecraft 1.20.3 and some fixes. I think I'll finish this by Christmas. This problem will be fixed
